services:
    gie.search.solr.query.common.facet_builder_visitor.tag:
        class: Gie\FacetBundle\Content\Query\Common\FacetBuilderVisitor\TagType
        tags:
            - {name: ezpublish.search.solr.query.content.facet_builder_visitor}
            - {name: ezpublish.search.solr.query.location.facet_builder_visitor}

    gie.search.solr.query.common.facet_builder_visitor.custom_date:
        class: Gie\FacetBundle\Content\Query\Common\FacetBuilderVisitor\CustomDateType
        tags:
            - {name: ezpublish.search.solr.query.content.facet_builder_visitor}
            - {name: ezpublish.search.solr.query.location.facet_builder_visitor}

    gie.search.solr.query.common.facet_builder_visitor.solr_file:
        class: Gie\FacetBundle\Content\Query\Common\FacetBuilderVisitor\SolrFieldType
        tags:
            - {name: ezpublish.search.solr.query.content.facet_builder_visitor}
            - {name: ezpublish.search.solr.query.location.facet_builder_visitor}

    gie.custom_tag_field_mapper:
        class: Gie\FacetBundle\FieldMapper\CustomTagFieldMapper
        arguments:
            - '@ezpublish.spi.persistence.content_handler'
            - '@ezpublish.spi.persistence.location_handler'
            - '@ezpublish.spi.persistence.content_type_handler'
        tags:
            - {name: ezpublish.search.solr.field_mapper.content}

    gie.location.tag_field_mapper:
        class: Gie\FacetBundle\FieldMapper\LocationCustomTagFieldMapper
        arguments:
            - '@ezpublish.spi.persistence.content_handler'
            - '@ezpublish.spi.persistence.location_handler'
            - '@ezpublish.spi.persistence.content_type_handler'
        tags:
            - {name: ezpublish.search.solr.field_mapper.location}

    gie.facet_search.content_type.helper:
        class: Gie\FacetBundle\Content\Search\Helper\ContentTypeFacetSearchHelper
        arguments:
            - '@ezpublish.api.service.content_type'
            - '@Logger'
        tags:
            - {name: gie.facet_search.helper, alias: 'content_type'}

    gie.facet_search.tag.helper:
        class: Gie\FacetBundle\Content\Search\Helper\TagFacetSearchHelper
        arguments:
            - '@eztags.api.service.tags'
            - '@Logger'
        tags:
            - {name: gie.facet_search.helper, alias: 'tags'}

    gie.facet_search.custom_date.helper:
        class: Gie\FacetBundle\Content\Search\Helper\CustomDateFacetSearchHelper
        arguments:
            - '@Logger'
        tags:
            - {name: gie.facet_search.helper, alias: 'custom_date'}

    gie.facet_search.solr_field.helper:
        class: Gie\FacetBundle\Content\Search\Helper\SolrFieldSearchHelper
        shared: false
        arguments:
            - '@Logger'
        tags:
            - {name: gie.facet_search.helper, alias: 'solr_field'}

    gie.facet.facet_loader:
        class: Gie\FacetBundle\Content\Search\Helper\FacetLoader

    gie.facet.search.helper:
        class: Gie\FacetBundle\Content\Search\Helper\FacetSearch
        arguments:
            -  '@gie.facet.facet_loader'
            -  '@ezpublish.api.service.inner_search'

    gie.search.solr.query.common.criterion_visitor.tag_in:
        class: Gie\FacetBundle\Content\Query\Content\CriterionVisitor\TagIn
        arguments:
            - '@eztags.api.service.tags'
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}
            - {name: ezpublish.search.solr.query.location.criterion_visitor}

    gie.search.solr.query.common.criterion_visitor.sorl_field_in:
        class: Gie\FacetBundle\Content\Query\Content\CriterionVisitor\SorlFieldIn
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}
            - {name: ezpublish.search.solr.query.location.criterion_visitor}
